// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserProfile user profile
//
// swagger:model user_profile
type UserProfile struct {

	// user primary email
	// Required: true
	Email string `json:"email" db:"email"`

	// id
	// Read Only: true
	ID string `json:"id,omitempty" db:"id"`

	// true if the profile is a global manager. This field is readonly
	// Read Only: true
	IsManager bool `json:"is_manager,omitempty" db:"is_manager"`

	// user nickname (name displayed to other users)
	Nickname string `json:"nickname,omitempty" db:"nickname"`

	// optional message provided during registration explaining why they want to join
	// Read Only: true
	RegistrationMessage *string `json:"registration_message,omitempty" db:"registration_message"`

	// User account state:
	// - pending: Registered but awaiting manager approval. Can authenticate but restricted from most operations.
	// - active: Fully approved user with full access.
	// - inactive: Deactivated account (e.g., system user).
	//
	// Read Only: true
	// Enum: ["pending","active","inactive"]
	State string `json:"state,omitempty" db:"state"`
}

// Validate validates this user profile
func (m *UserProfile) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserProfile) validateEmail(formats strfmt.Registry) error {

	if err := validate.RequiredString("email", "body", m.Email); err != nil {
		return err
	}

	return nil
}

var userProfileTypeStatePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["pending","active","inactive"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		userProfileTypeStatePropEnum = append(userProfileTypeStatePropEnum, v)
	}
}

const (

	// UserProfileStatePending captures enum value "pending"
	UserProfileStatePending string = "pending"

	// UserProfileStateActive captures enum value "active"
	UserProfileStateActive string = "active"

	// UserProfileStateInactive captures enum value "inactive"
	UserProfileStateInactive string = "inactive"
)

// prop value enum
func (m *UserProfile) validateStateEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, userProfileTypeStatePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *UserProfile) validateState(formats strfmt.Registry) error {
	if swag.IsZero(m.State) { // not required
		return nil
	}

	// value enum
	if err := m.validateStateEnum("state", "body", m.State); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this user profile based on the context it is used
func (m *UserProfile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateIsManager(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRegistrationMessage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateState(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserProfile) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *UserProfile) contextValidateIsManager(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "is_manager", "body", m.IsManager); err != nil {
		return err
	}

	return nil
}

func (m *UserProfile) contextValidateRegistrationMessage(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "registration_message", "body", m.RegistrationMessage); err != nil {
		return err
	}

	return nil
}

func (m *UserProfile) contextValidateState(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "state", "body", m.State); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserProfile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserProfile) UnmarshalBinary(b []byte) error {
	var res UserProfile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
