// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptInvitation(arg1, arg2) {
  return window['go']['main']['App']['AcceptInvitation'](arg1, arg2);
}

export function AddServer(arg1, arg2) {
  return window['go']['main']['App']['AddServer'](arg1, arg2);
}

export function ApprovePendingRegistration(arg1, arg2) {
  return window['go']['main']['App']['ApprovePendingRegistration'](arg1, arg2);
}

export function AutoConnect(arg1) {
  return window['go']['main']['App']['AutoConnect'](arg1);
}

export function BuildAndSaveRace(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildAndSaveRace'](arg1, arg2, arg3);
}

export function ChangeMyApikey(arg1) {
  return window['go']['main']['App']['ChangeMyApikey'](arg1);
}

export function CheckNtvdmSupport() {
  return window['go']['main']['App']['CheckNtvdmSupport']();
}

export function CheckWine32Support() {
  return window['go']['main']['App']['CheckWine32Support']();
}

export function ClipboardGetText() {
  return window['go']['main']['App']['ClipboardGetText']();
}

export function ClipboardSetText(arg1) {
  return window['go']['main']['App']['ClipboardSetText'](arg1);
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function CreateSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3);
}

export function CreateUserProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateUserProfile'](arg1, arg2, arg3);
}

export function DeclineInvitation(arg1, arg2) {
  return window['go']['main']['App']['DeclineInvitation'](arg1, arg2);
}

export function DeleteRace(arg1, arg2) {
  return window['go']['main']['App']['DeleteRace'](arg1, arg2);
}

export function DeleteSession(arg1, arg2) {
  return window['go']['main']['App']['DeleteSession'](arg1, arg2);
}

export function DeleteUserProfile(arg1, arg2) {
  return window['go']['main']['App']['DeleteUserProfile'](arg1, arg2);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function DownloadHistoricBackup(arg1, arg2) {
  return window['go']['main']['App']['DownloadHistoricBackup'](arg1, arg2);
}

export function DownloadRace(arg1, arg2) {
  return window['go']['main']['App']['DownloadRace'](arg1, arg2);
}

export function DownloadSessionBackup(arg1, arg2) {
  return window['go']['main']['App']['DownloadSessionBackup'](arg1, arg2);
}

export function FSExists(arg1, arg2) {
  return window['go']['main']['App']['FSExists'](arg1, arg2);
}

export function FSListAll(arg1) {
  return window['go']['main']['App']['FSListAll'](arg1);
}

export function FSMkdir(arg1, arg2, arg3) {
  return window['go']['main']['App']['FSMkdir'](arg1, arg2, arg3);
}

export function FSReadFile(arg1, arg2) {
  return window['go']['main']['App']['FSReadFile'](arg1, arg2);
}

export function FSReaddir(arg1, arg2) {
  return window['go']['main']['App']['FSReaddir'](arg1, arg2);
}

export function FSRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['FSRename'](arg1, arg2, arg3);
}

export function FSRmdir(arg1, arg2) {
  return window['go']['main']['App']['FSRmdir'](arg1, arg2);
}

export function FSStat(arg1, arg2) {
  return window['go']['main']['App']['FSStat'](arg1, arg2);
}

export function FSUnlink(arg1, arg2) {
  return window['go']['main']['App']['FSUnlink'](arg1, arg2);
}

export function FSWriteFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FSWriteFile'](arg1, arg2, arg3, arg4);
}

export function GenerateAnimatedMap(arg1) {
  return window['go']['main']['App']['GenerateAnimatedMap'](arg1);
}

export function GenerateMap(arg1) {
  return window['go']['main']['App']['GenerateMap'](arg1);
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetConnectionState(arg1) {
  return window['go']['main']['App']['GetConnectionState'](arg1);
}

export function GetCurrentAPIKey(arg1) {
  return window['go']['main']['App']['GetCurrentAPIKey'](arg1);
}

export function GetInvitations(arg1) {
  return window['go']['main']['App']['GetInvitations'](arg1);
}

export function GetLatestTurn(arg1, arg2) {
  return window['go']['main']['App']['GetLatestTurn'](arg1, arg2);
}

export function GetMyRaces(arg1) {
  return window['go']['main']['App']['GetMyRaces'](arg1);
}

export function GetOrdersStatus(arg1, arg2) {
  return window['go']['main']['App']['GetOrdersStatus'](arg1, arg2);
}

export function GetPendingRegistrations(arg1) {
  return window['go']['main']['App']['GetPendingRegistrations'](arg1);
}

export function GetRaceTemplate(arg1) {
  return window['go']['main']['App']['GetRaceTemplate'](arg1);
}

export function GetRules(arg1, arg2) {
  return window['go']['main']['App']['GetRules'](arg1, arg2);
}

export function GetSentInvitations(arg1) {
  return window['go']['main']['App']['GetSentInvitations'](arg1);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetSession(arg1, arg2) {
  return window['go']['main']['App']['GetSession'](arg1, arg2);
}

export function GetSessionPlayerRace(arg1, arg2) {
  return window['go']['main']['App']['GetSessionPlayerRace'](arg1, arg2);
}

export function GetSessions(arg1) {
  return window['go']['main']['App']['GetSessions'](arg1);
}

export function GetTurn(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTurn'](arg1, arg2, arg3, arg4);
}

export function GetUserProfiles(arg1) {
  return window['go']['main']['App']['GetUserProfiles'](arg1);
}

export function HasStarsExe(arg1, arg2) {
  return window['go']['main']['App']['HasStarsExe'](arg1, arg2);
}

export function InviteUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['InviteUser'](arg1, arg2, arg3);
}

export function JoinSession(arg1, arg2) {
  return window['go']['main']['App']['JoinSession'](arg1, arg2);
}

export function LaunchStars(arg1, arg2) {
  return window['go']['main']['App']['LaunchStars'](arg1, arg2);
}

export function LoadRaceFileConfig(arg1, arg2) {
  return window['go']['main']['App']['LoadRaceFileConfig'](arg1, arg2);
}

export function LogDebug(arg1) {
  return window['go']['main']['App']['LogDebug'](arg1);
}

export function OpenGameDir(arg1, arg2) {
  return window['go']['main']['App']['OpenGameDir'](arg1, arg2);
}

export function PromoteMember(arg1, arg2, arg3) {
  return window['go']['main']['App']['PromoteMember'](arg1, arg2, arg3);
}

export function QuitSession(arg1, arg2) {
  return window['go']['main']['App']['QuitSession'](arg1, arg2);
}

export function Register(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3, arg4);
}

export function RejectPendingRegistration(arg1, arg2) {
  return window['go']['main']['App']['RejectPendingRegistration'](arg1, arg2);
}

export function RemoveServer(arg1) {
  return window['go']['main']['App']['RemoveServer'](arg1);
}

export function ReorderPlayers(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderPlayers'](arg1, arg2, arg3);
}

export function ReorderServers(arg1) {
  return window['go']['main']['App']['ReorderServers'](arg1);
}

export function ResetUserApikey(arg1, arg2) {
  return window['go']['main']['App']['ResetUserApikey'](arg1, arg2);
}

export function SaveGif(arg1) {
  return window['go']['main']['App']['SaveGif'](arg1);
}

export function SaveMap(arg1) {
  return window['go']['main']['App']['SaveMap'](arg1);
}

export function SelectServersDir() {
  return window['go']['main']['App']['SelectServersDir']();
}

export function SelectWinePrefixesDir() {
  return window['go']['main']['App']['SelectWinePrefixesDir']();
}

export function SetAutoDownloadStars(arg1) {
  return window['go']['main']['App']['SetAutoDownloadStars'](arg1);
}

export function SetEnableBrowserStars(arg1) {
  return window['go']['main']['App']['SetEnableBrowserStars'](arg1);
}

export function SetNotificationIcon(arg1) {
  return window['go']['main']['App']['SetNotificationIcon'](arg1);
}

export function SetPlayerReady(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPlayerReady'](arg1, arg2, arg3);
}

export function SetRules(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRules'](arg1, arg2, arg3);
}

export function SetServersDir(arg1) {
  return window['go']['main']['App']['SetServersDir'](arg1);
}

export function SetSessionRace(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSessionRace'](arg1, arg2, arg3);
}

export function SetUseWine(arg1) {
  return window['go']['main']['App']['SetUseWine'](arg1);
}

export function SetWinePrefixesDir(arg1) {
  return window['go']['main']['App']['SetWinePrefixesDir'](arg1);
}

export function SetZoomLevel(arg1) {
  return window['go']['main']['App']['SetZoomLevel'](arg1);
}

export function StartGame(arg1, arg2) {
  return window['go']['main']['App']['StartGame'](arg1, arg2);
}

export function UpdateServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateServer'](arg1, arg2, arg3);
}

export function UploadRace(arg1, arg2) {
  return window['go']['main']['App']['UploadRace'](arg1, arg2);
}

export function ValidateRaceConfig(arg1) {
  return window['go']['main']['App']['ValidateRaceConfig'](arg1);
}
