// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AcceptInvitation(arg1:string,arg2:string):Promise<main.SessionInfo>;

export function AddServer(arg1:string,arg2:string):Promise<main.ServerInfo>;

export function ApprovePendingRegistration(arg1:string,arg2:string):Promise<string>;

export function AutoConnect(arg1:string):Promise<main.ConnectResult>;

export function BuildAndSaveRace(arg1:string,arg2:main.RaceConfig,arg3:string):Promise<main.RaceInfo>;

export function ChangeMyApikey(arg1:string):Promise<string>;

export function CheckNtvdmSupport():Promise<main.NtvdmCheckResult>;

export function CheckWine32Support():Promise<main.WineCheckResult>;

export function ClipboardGetText():Promise<string>;

export function ClipboardSetText(arg1:string):Promise<void>;

export function Connect(arg1:string,arg2:string,arg3:string):Promise<main.ConnectResult>;

export function CreateSession(arg1:string,arg2:string,arg3:boolean):Promise<main.SessionInfo>;

export function CreateUserProfile(arg1:string,arg2:string,arg3:string):Promise<main.UserProfileInfo>;

export function DeclineInvitation(arg1:string,arg2:string):Promise<void>;

export function DeleteRace(arg1:string,arg2:string):Promise<void>;

export function DeleteSession(arg1:string,arg2:string):Promise<void>;

export function DeleteUserProfile(arg1:string,arg2:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DownloadHistoricBackup(arg1:string,arg2:string):Promise<void>;

export function DownloadRace(arg1:string,arg2:string):Promise<string>;

export function DownloadSessionBackup(arg1:string,arg2:string):Promise<void>;

export function FSExists(arg1:string,arg2:string):Promise<boolean>;

export function FSListAll(arg1:string):Promise<Array<main.FSFileEntry>>;

export function FSMkdir(arg1:string,arg2:string,arg3:number):Promise<void>;

export function FSReadFile(arg1:string,arg2:string):Promise<Array<number>>;

export function FSReaddir(arg1:string,arg2:string):Promise<Array<string>>;

export function FSRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FSRmdir(arg1:string,arg2:string):Promise<void>;

export function FSStat(arg1:string,arg2:string):Promise<main.FSStatResult>;

export function FSUnlink(arg1:string,arg2:string):Promise<void>;

export function FSWriteFile(arg1:string,arg2:string,arg3:Array<number>,arg4:number):Promise<void>;

export function GenerateAnimatedMap(arg1:main.AnimatedMapRequest):Promise<string>;

export function GenerateMap(arg1:main.MapGenerateRequest):Promise<string>;

export function GetAppSettings():Promise<main.AppSettingsInfo>;

export function GetConnectionState(arg1:string):Promise<main.ConnectionState>;

export function GetCurrentAPIKey(arg1:string):Promise<string>;

export function GetInvitations(arg1:string):Promise<Array<main.InvitationInfo>>;

export function GetLatestTurn(arg1:string,arg2:string):Promise<main.TurnFilesInfo>;

export function GetMyRaces(arg1:string):Promise<Array<main.RaceInfo>>;

export function GetOrdersStatus(arg1:string,arg2:string):Promise<main.OrdersStatusInfo>;

export function GetPendingRegistrations(arg1:string):Promise<Array<main.UserProfileInfo>>;

export function GetRaceTemplate(arg1:string):Promise<main.RaceConfig>;

export function GetRules(arg1:string,arg2:string):Promise<main.RulesInfo>;

export function GetSentInvitations(arg1:string):Promise<Array<main.InvitationInfo>>;

export function GetServers():Promise<Array<main.ServerInfo>>;

export function GetSession(arg1:string,arg2:string):Promise<main.SessionInfo>;

export function GetSessionPlayerRace(arg1:string,arg2:string):Promise<main.RaceInfo>;

export function GetSessions(arg1:string):Promise<Array<main.SessionInfo>>;

export function GetTurn(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<main.TurnFilesInfo>;

export function GetUserProfiles(arg1:string):Promise<Array<main.UserProfileInfo>>;

export function HasStarsExe(arg1:string,arg2:string):Promise<boolean>;

export function InviteUser(arg1:string,arg2:string,arg3:string):Promise<main.InvitationInfo>;

export function JoinSession(arg1:string,arg2:string):Promise<main.SessionInfo>;

export function LaunchStars(arg1:string,arg2:string):Promise<void>;

export function LoadRaceFileConfig(arg1:string,arg2:string):Promise<main.RaceConfig>;

export function LogDebug(arg1:string):Promise<void>;

export function OpenGameDir(arg1:string,arg2:string):Promise<void>;

export function PromoteMember(arg1:string,arg2:string,arg3:string):Promise<void>;

export function QuitSession(arg1:string,arg2:string):Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RejectPendingRegistration(arg1:string,arg2:string):Promise<void>;

export function RemoveServer(arg1:string):Promise<void>;

export function ReorderPlayers(arg1:string,arg2:string,arg3:Array<Record<string, any>>):Promise<void>;

export function ReorderServers(arg1:Array<main.ServerOrder>):Promise<void>;

export function ResetUserApikey(arg1:string,arg2:string):Promise<string>;

export function SaveGif(arg1:main.GifSaveRequest):Promise<void>;

export function SaveMap(arg1:main.MapSaveRequest):Promise<void>;

export function SelectServersDir():Promise<main.AppSettingsInfo>;

export function SelectWinePrefixesDir():Promise<main.AppSettingsInfo>;

export function SetAutoDownloadStars(arg1:boolean):Promise<main.AppSettingsInfo>;

export function SetEnableBrowserStars(arg1:boolean):Promise<main.AppSettingsInfo>;

export function SetNotificationIcon(arg1:Array<number>):Promise<void>;

export function SetPlayerReady(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetRules(arg1:string,arg2:string,arg3:main.RulesInfo):Promise<main.RulesInfo>;

export function SetServersDir(arg1:string):Promise<main.AppSettingsInfo>;

export function SetSessionRace(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetUseWine(arg1:boolean):Promise<main.AppSettingsInfo>;

export function SetWinePrefixesDir(arg1:string):Promise<main.AppSettingsInfo>;

export function SetZoomLevel(arg1:number):Promise<main.AppSettingsInfo>;

export function StartGame(arg1:string,arg2:string):Promise<void>;

export function UpdateServer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UploadRace(arg1:string,arg2:string):Promise<main.RaceInfo>;

export function ValidateRaceConfig(arg1:main.RaceConfig):Promise<main.RaceValidationResult>;
